
spring:
  datasource:
    url: jdbc:sqlserver://azureserver401.database.windows.net:1433;database=newAzuredb;user=devesh@azureserver401;password=Password@123;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    show-sql: 'true'
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect
server:
  port: '8088'




















































